version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "postgresdb"
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
